## ********************************************************************* ##
## Copyright 2016                                                        ##
## David Farmer, Greg Hartman, Alex Jordan, Carly Vollet                 ##
##                                                                       ##
## This file is part of APEX Calculus                                    ##
##                                                                       ##
## ********************************************************************* ##

#######################
# DO NOT EDIT THIS FILE
#######################

#   1) Make a copy of Makefile.paths.original
#      as Makefile.paths, which git will ignore.
#   2) Edit Makefile.paths to provide full paths to the root folders
#      of your local clones of the project repository and the mathbook
#      repository as described below.
#   3) The files Makefile and Makefile.paths.original
#      are managed by git revision control and any edits you make to
#      these will conflict. You should only be editing Makefile.paths.

##############
# Introduction
##############

# This is not a "true" makefile, since it does not
# operate on dependencies.  It is more of a shell
# script, sharing common configurations

######################
# System Prerequisites
######################

#   install         (system tool to make directories)
#   xsltproc        (xml/xsl text processor)
#   xmllint         (only to check source against DTD)
#   <helpers>       (PDF viewer, web browser, pager, Sage executable, etc)

#####
# Use
#####

#	A) Navigate to the location of this file
#	B) At command line:  make <some-target-from-the-options-below>

# The included file contains customized versions
# of locations of the principal components of this
# project and names of various helper executables
include Makefile.paths

###################################
# These paths are subdirectories of
# the project distribution
###################################
SRC       = $(PRJ)/ptx
IMGSRC    = $(PRJ)/external-images
OUTPUT    = $(PRJ)/output
PUB       = $(PRJ)/publication
XSL       = $(PRJ)/xsl

# The project's root file
MAINFILE  = $(SRC)/apex.ptx

# The project's styling files
PUBFILE   = $(PUB)/publication.xml

# These paths are subdirectories of
# the PreTeXt distribution
PTXXSL = $(PTX)/xsl

# These paths are subdirectories of the output
# folder for different output formats
PRINTOUT   = $(OUTPUT)/print
HTMLOUT    = $(OUTPUT)/html
WWOUT      = $(OUTPUT)/webwork-representations
IMGOUT     = $(OUTPUT)/images
PGOUT      = $(OUTPUT)/pg
PRVOUT     = $(OUTPUT)/preview
VIDEOOUT   = $(OUTPUT)/video
SAGEPLOT   = $(OUTPUT)/sageplot

# The WeBWorK server we use
#SERVER = "(https://webwork-dev.aimath.org,anonymous,anonymous,anonymous,anonymous)"
SERVER = "(https://webwork-ptx.aimath.org,anonymous,anonymous,anonymous,anonymous)"
#SERVER = "(https://webwork.pcc.edu,orcca,orcca,anonymous,orcca)"
#SERVER = http://localhost

pg-macros:
	$(PTX)/pretext/pretext -c pg-macros $(MAINFILE)

webwork-representations:
	-rm -r $(WWOUT) || :
	install -d $(WWOUT)
	$(PTX)/pretext/pretext -vv -a -c webwork -d $(WWOUT) -s $(SERVER) $(MAINFILE)

pg:
	-rm -r $(PGOUT) || :
	install -d $(PGOUT)
	cd $(PGOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam chunk.level 2 $(PTXXSL)/pretext-ww-problem-sets.xsl $(MAINFILE)

html:
	install -d $(OUTPUT)
	-rm -r $(HTMLOUT) || :
	install -d $(HTMLOUT)
	install -d $(HTMLOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(IMGOUT) $(HTMLOUT) || :
	cp -a $(IMGSRC) $(HTMLOUT) || :
	cp -a $(WWOUT)/*.png $(HTMLOUT)/images || :
	cp -a $(WWOUT)/*.svg $(HTMLOUT)/images || :
	cd $(HTMLOUT); \
	xsltproc --xinclude --stringparam publisher $(PUBFILE) --stringparam exercise.inline.hint yes --stringparam exercise.inline.answer yes --stringparam exercise.inline.solution yes --stringparam exercise.divisional.hint yes --stringparam exercise.divisional.answer yes --stringparam exercise.divisional.solution yes --stringparam webwork.divisional.static no $(PTXXSL)/pretext-html.xsl $(MAINFILE); \

images:
	install -d $(OUTPUT)
	-rm $(IMGOUT) || :
	install -d $(IMGOUT)
	$(PTX)/pretext/pretext -c latex-image -p $(PUBFILE) -f all -d $(IMGOUT) $(MAINFILE)

video-preview:
	install -d $(OUTPUT)
	-rm $(VIDEOOUT) || :
	install -d $(VIDEOOUT)
	$(PTX)/pretext/pretext -c youtube -p $(PUBFILE) -d $(VIDEOOUT) $(MAINFILE)

sageplot:
	install -d $(OUTPUT)
	-rm $(SAGEPLOT) || :
	install -d $(SAGEPLOT)
	$(PTX)/pretext/pretext -c sageplot -f pdf -p $(PUBFILE) -d $(SAGEPLOT) $(MAINFILE)

pdf:
	install -d $(OUTPUT)
	-rm -r $(PRINTOUT) || :
	install -d $(PRINTOUT)
	install -d $(PRINTOUT)/images
	install -d $(IMGOUT)
	install -d $(IMGSRC)
	cp -a $(WWOUT)/*.png $(PRINTOUT)/images || :
	cp -a $(IMGSRC) $(PRINTOUT) || :
	cp -a $(VIDEOOUT)/*.jpg $(PRINTOUT)/images || :
	cp -a $(SAGEPLOT)/*.pdf $(PRINTOUT)/images || :
	cd $(PRINTOUT); \
	xsltproc -xinclude --stringparam publisher $(PUBFILE) --stringparam latex.print 'yes' --stringparam latex.pageref 'no' --stringparam latex.sides 'two' --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no --stringparam exercise.divisional.hint no $(PTXXSL)/pretext-latex.xsl $(MAINFILE) > apex.tex; \
	xelatex apex.tex; \
	xelatex apex.tex; \


###########
# Utilities
###########

check:
	install -d $(OUTPUT)
	-rm $(OUTPUT)/jingreport.txt
	-java -classpath ~/jing-trang/build -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration -jar ~/jing-trang/build/jing.jar $(PTX)/schema/pretext.rng $(MAINFILE) > $(OUTPUT)/jingreport.txt
	less $(OUTPUT)/jingreport.txt
